In [16]:
# Problem 1: Create a 3×3 random matrix and compute its inverse using numpy.linalg.inv().
import numpy as np

# A singular matrix for testing.
# matrix = np.array([[1, 2, 3],
#                    [2, 4, 6],
#                    [7, 8, 9]])

# A random matrix generated by NumPy
matrix = np.random.rand(3, 3)

determinant = np.linalg.det(matrix)

if determinant != 0:
    inverse = np.linalg.inv(matrix)
    print("Matrix:\n", matrix)
    print("Inverse:\n", inverse)

else:
    print("Matrix is non-invertible i.e., the given matrix is singular.")

Matrix:
 [[0.91749798 0.15080638 0.9756246 ]
 [0.05850817 0.09668991 0.42441926]
 [0.93216884 0.86750621 0.76122128]]
Inverse:
 [[ 1.15185021 -2.86047998  0.11858496]
 [-1.37280489  0.82513836  1.29940878]
 [ 0.15396035  2.56251069 -0.31237486]]


In [17]:
# Problem 2: Compute the dot product of two randomly generated vectors using numpy.dot().

# Generate two random vectors

v1 = np.random.rand(4)
v2 = np.random.rand(4)

# Print the vectors
print(f"The first vector is: {v1}")
print(f"The second vector is: {v2}")

# Compute the dot product
dot_product = np.dot(v1, v2)

print("The dot product is: ", dot_product)

The first vector is: [0.16688488 0.95633886 0.01181348 0.26859054]
The second vector is: [0.04302312 0.88449577 0.61817634 0.1882492 ]
The dot product is:  0.9109223541954463


In [23]:
# Problem 3: Perform matrix-vector multiplication with NumPy.

# Define a matrix of 4 x 4
matrix = np.array([[1, 2, 3, 4],
                   [1, 1, 2, 3],
                   [2, 1, 0, 0],
                   [0, 1, 1, 1]])

# Define a vector of 4 x 1
v = np.array([1, 1, 1, 1])

# Multiplication using np.dot(), result will be 4 x 1 matrix
# result = np.dot(matrix, v) 

# Different approach
result = matrix @ v

print("Given Matrix:\n", matrix)
print("\n")
print("Given Vector: ", v)
print("\n")
print(f"The result of multiplication is: \n{result}")

Given Matrix:
 [[1 2 3 4]
 [1 1 2 3]
 [2 1 0 0]
 [0 1 1 1]]


Given Vector:  [1 1 1 1]


The result of multiplication is: 
[10  7  3  3]


In [ ]:
# Problem 4: Solve a system of linear equations using scipy.linalg.solve().
%pip install scipy
from scipy import linalg

In [36]:
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [7, 8, 9]])
vector = np.array([1, 2, 3])

try:
    result = linalg.solve(matrix, vector)
    print("Solution: ", result)

except linalg.LinAlgError:
    print("The matrix is singular.")

The matrix is singular.
